name: Deploy

on:
  push:
    branches: ["main", "staging"]

jobs:
  define_environment:
    runs-on: ubuntu-latest
    name: Define Environment
    steps:
      - id: define_environment
        run: |
          if [ "${{ github.event_name }}" == 'push' ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "push-production"
            echo "env_name=production" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == 'push' ] && [ "${{ github.ref }}" = "refs/heads/staging" ]; then
            echo "push-staging"
            echo "env_name=staging" >> $GITHUB_OUTPUT
          else
            echo "unknown"
            echo "env_name=unknown" >> $GITHUB_OUTPUT
          fi
    outputs:
      env_name: ${{ steps.define_environment.outputs.env_name }}

  push_keys:
    runs-on: ubuntu-latest
    name: Release
    needs: [define_environment]
    if: ${{ needs.define_environment.outputs.env_name != 'unknown' }}
    environment: ${{ needs.define_environment.outputs.env_name }}
    steps:
      - uses: actions/checkout@v3
      - run: ./deployment/deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          KEY_BUCKETS: ${{ secrets.KEY_BUCKETS }}
